package com.lifestyle.buddydetagging.constant;

public interface GeneralConstant {


    String GSTINFORMAT_REGEX = "[0-9]{2}[a-zA-Z]{5}[0-9]{4}[a-zA-Z]{1}[1-9A-Za-z]{1}[Z]{1}[0-9a-zA-Z]{1}";
    String GSTN_CODEPOINT_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    long TIME_OUT = 1200;
    String KEY_LOCAL_NOTIF = "KEY_LOCAL_NOTIF";
    int LOGIN_DETAILS = 101;
    int REGISTRATION_DEVICE_VALIDATION = 102;
    int REGISTRATION_VALID_EMPLOYEE = 103;
    int REGISTRATION_NEWDEVICE = 104;
    int REGISTRATION_FETCH_STORE = 105;
    int REGISTRATION_SAVE__DETAILS = 106;
    int UPDATE_FCM_TOKEN_REQUEST = 107;
    int CHECK_APP_VERSION = 108;
    int REGISTRATION_GETALLOUSTORE = 106;
    int REGISTRATION_COMPANY_REGISTERDEVICE = 107;
    int SOH_ITEM_DETAILS = 109;

    //ADMIN
    int DEVICE_DETAILS =109;
    int APPROVEREJECT_DEVICE = 110;
    int DEVICE_DETAIL_USER = 111;
    int USER_DETAIL = 112;
    int DEACTIVATE_USER_ACCOUNT = 113;
    int INACTIVE_USER_ACCOUNT = 114;
    int INACTIVE_USER_ACCOUNT_DETAILS = 115;
    int INACTIVE_USER_APPROVE = 116;
    int MORESTORE_USER_LIST = 117;
    int STORE_DETAILS = 118;
    int ADD_DELETE_USER_STORE_ACCOUNTDETAILS = 119;
    int APPROVEREJECT_REQUESTEDDEVICE = 120;
    int MORESTORE_APPROVEREJECT = 121;
    int ADDMORE_FETCH_STORE =122;
    int APPROVE_STOREINFO =133;
    int FETCH_ACTOR_ROLE =155;
    int FETCH_EMP_DETAIL_CROLE =156;
    int UPDATE_ROLE_CROLE = 157;

    //EOSS
    int EOSS_DETAILS = 158;

    //ACS
    int GET_ACS_CUSTOMER_DETAILS =123;
    int GET_ACS_VALIDATE_ITEM =124;
    int GET_ACS_STORE_DATA =125;
    int GET_ACS_SAVE_CUSTOMER_DETAILS =127;
    int GET_ACS_ALTER_FORM_LIST =128;
    int GET_ACS_ALTER_SINGLEFORM_DATA =129;
    int GET_ACS_SUBMIT_READYFORDELIVERY =130;
    int GET_ACS_DELIVERY_FORM =131;
    int GET_ACS_DELIVERY_SUBMIT =132;

    //ACS-Dashboard
    int STORE_CLOSING =150;
    int SUMMARY_ACS =151;
    //ACS-Tailor
    int GET_ACS_RECEIVED_LIST =152;
    int GET_ACS_ALTER_DETAILS =153;
    int GET_ACS_UPDATE_ALT_FRM_ALTRED =154;

    //MissingBarcode
    int GET_MISSING_BARCODE = 159;
    int GET_MISSING_BARCODE_DETAIS = 160;
    int GET_MISSING_BARCODE_PRINT = 161;


    //    int DEVICE_DETAILS =107;
    int WASNOW_SUNMI_REQUEST =200;
    int WASNOW_SuppourtedFocusedModes_REQUEST =201;
    int WASNOW_NOT_SuppourtedFocusedModes_REQUEST =202;

    int PROMO_SUNMI_REQUEST =203;
    int PROMO_SuppourtedFocusedModes_REQUEST =204;
    int PROMO_NOT_SuppourtedFocusedModes_REQUEST =205;

    int ABOUTCART_GETMASTERDATA=206;
    int ABOUTCART_CHECKINCHECKOUT=207;
    int ABOUTCART_ITEMVALIDAUDIT=208;
    int ABOUTCART_SUBMITTRANSACTIONDETAILS=209;
    int ABOUTCART_GETREASON=210;
    int ABOUTCART_GETVARIANCE=211;
    int ABOUTCART_UPDATETRANSACTIONDETAILS=212;

    int SETTINGS_CHANGEPASSWORD=213;
    int SETTINGS_GETPROFILEINFO=214;
    int SETTINGS_GETALLSTORE=215;
    int SETTINGS_CHECKINCHECKOUTFRA=216;
    int SETTINGS_CHECKINCHECKOUTOSD=217;
    int SETTINGS_CHECKINCHECKOUTCm=218;
    int SETTINGS_UPDATEPROFILEINFO=219;

    int PROMO_ITEMDETAILS=220;

    int SOH_GETDIVISIONLIST=221;
    int SOH_ITEMDETAILS=222;
    int SOH_OPTIONDETAILS=223;
    int SOH_STYLE=224;
    int SOH_BUDDYSTORE=224;
    int SOH_SMS=225;

    int SHELFDGE_ITEMDETAILS=226;
    int SHELFDGE_EOSSDETAILS=227;
    int SHELFDGE_StyLE=228;
    int SHELFDGE_PRINTER=229;

    /*FRA Constants*/
    int ZONE_LIST = 108;
    int FRA_CHECKIN = 200;
    int FRA_CHECKOUT = 109;
    int FRA_DASHBOARD = 201;

    int FRS_CONCEPTLIST=230;
    int FRS_CHECKINCHECKOUT=231;
    int FRS_FETCHREQUESTLIST=232;
    int FRS_UPADTEREQUESTSTATUSWITHREASON=233;
    int FRS_REASONDETAILS=234;
    int FRS_GETREQUESTDETAILS=235;
    int FRS_GETITEMMATCHING=236;

    int FRA_ZONELIST=237;
    int FRA_CHECKINCHECKOUT=238;
    int FRA_DASHBOARDDETAILS=239;
    int FRA_FITTINGROOM=240;
    int FRA_SOH=241;
    int FRA_SendRequestDetails=242;
    int FRA_SMS=243;
    int FRA_GETLIST=244;
    int FRA_WCBLIST=245;
    int FRA_WCBUPDATE=300;
    int FRA_UPDATE=245;


    int FORGOT_PASSWORD=301;
    int CHANGE_PASSWORD=302;

    int WasNOW_Details=401;
    int Promo_Details=401;

    int OSD_CHECKINCHECKOUT = 246;
    int OSD_CHECKINCHECKOUT_STATUS = 247;

    int OSD_REASON_LIST = 248;
    int OSD_ORDER_LIST = 249;
    int OSD_UPDATE_ORDER_STATUS = 250;

    int OSD_LINE_ITEM_LIST = 251;
    int OSD_CONFIRM_ORDER = 252;

    int OSD_BIN_LIST = 253;
    int OSD_SUBMIT_BIN_TO_ORDER = 254;

    int OSD_LINE_ITEM_DETAILS = 255;
    int OSD_UPDATE_REQUEST_STATUS_WITH_REASON = 256;
    int OSD_ITEM_MATCHING = 257;

    int OSD_MAX_ORDER_LIST = 258;
    //int OSD_MAX_ORDER_LIST = 259;

    int OSD_MAX_SVI_ITEM_LIST = 260;
    int OSD_MAX_UPDATE_REQUEST_STATUS_WITH_REASON = 261;



    int OSD_MAX_SUBMIT_BIN_TO_ORDER = 262;
    int OSD_MAX_UPDATE_ORDER_STATUS = 263;

    int OSD_MAX_REASON_LIST = 264;
    int OSD_MAX_CONFIRM_ORDER = 265;

    int OSD_MAX_LINE_ITEM_LIST = 266;

    int SETTING_TAB_LIST = 271;
    int SETTING_TAB_VALIDATE = 272;
    int SETTING_TAB_UPDATE = 273;


    //Push Notification

    int SMS_PUSH_NOTIFICATION=280;

    //SVI Dashboard
    int SVI_DASHBOARD = 281;

    int OSD_DIVISION_BASED_DATA = 282;
    int ITEM_BIN_LIST_DATA = 282;

    int ORDER_HISTORY_DATA = 283;
    int ADDITIONAL_CAPACITY_LIST = 284;
    int ADDITIONAL_CAPACITY_ADD = 285;

    // dt: 15-07-2021
    int SVI_ORDER_ITEM_DETAIL_LIST = 286;
    int SVI_ORDER_CONFIRM_FOR_PICK_FAILED = 287;



    int FRA_REASON_LIST = 444;
    int STOCK_CONSOLIDATION_LIST = 500;
    int STORE_SALE_PERFORMANCE = 501;
    int STOCK_CONSOLIDATION_DETAIL = 502;
    int CHART_SALE_PERFORMANCE = 503;
    int HOURLY_SALE = 504;
    int SALE_DAHBOARD_USER_ACCESS = 505;
    int STORE_PRODUCT = 506;
    int COMPARE_STORE_LIST = 507;
    int GW_SEARCH_CUSTOMER_DETAIL = 600;
    int GW_ITEM_VALIDATION = 601;
    int GW_SAVE_CUSTOMER = 602;
    int GW_READY_TO_COLLECT_LIST = 603;
    int GW_SINGLE_READY_TO_COLLECL = 604;
    int GW_COLLECT_BY = 605;
    int GW_DELIVERY_REFRENCE_NO = 606;
    int GW_DELIVERY_MOBILE_NO = 607;
    int GW_DELIVERED = 608;
    int FCM_TOKEN = 100;
    int SA_STATUS = 610;
    int FETCH_ACTOR_DETAIL = 611;
    int GW_SEARCH_BY_INVOICE = 612;
    int VALIDATE_EMPLOYEE = 612;
}
